services:
  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: my-node-app-container
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
